env:  "prod" # dev, test, prod, local
name_project: "sso_auth"
# max_concurrent_connections: 5
#host: "localhost"
jwt_key: ErkkiSofit9944
token_ttl: 3600
grpc:
  ip: "0.0.0.0"
  port: "50051"
  read-timeout: "10s"
  write-timeout: "10s"

mongodb:
  host: 127.0.0.1
  port: "38841"
  username: sso_auth
  password: ErkkiSofit9944
  database: sso_auth
  auth_db: admin
  mongodb_collection:
    users: users
#    port: ":50051"
#    mongo_uri: "mongodb://localhost:38838"
#    database: "sso_auth"
#    password: "ErkkiSofit9944"
