name: Деплой sso_auth

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04

    env:
      NAME_APP: sso_auth
      NAME_DB: sso_auth
      SERVER_IP: 85.143.219.160
      GO_PORT: 50051
      DB_PORT: 38840
      DB_USER: sso_auth
      DB_PATH: /root/data/db/mongodb/
      GO_MAIN_FILE: /server/main.go
      ROOT_DIR: /root/apps/
      CONFIG_APP: config_prod.yaml
      PATH_SERVICE: /etc/systemd/system/ # Путь к systemd конфигу
      PROTO_DIR: /proto/
      GEN_DIR: /gen/
      GO_VERSION: 1.24.2

    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v4

      - name: Настройка SSH соединения
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Проверка и установка Go
        run: |
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << 'EOF'
          REQUIRED_GO_VERSION="${{ env.GO_VERSION }}"
          set -euo pipefail
          
          CURRENT_GO="$(go version 2>/dev/null || echo 'none')"
          if [[ "$CURRENT_GO" == *"go$REQUIRED_GO_VERSION"* ]]; then
            echo "✅ Go $REQUIRED_GO_VERSION уже установлен"
          else
            echo "⬇️ Установка Go $REQUIRED_GO_VERSION..."
            curl -fsSL https://go.dev/dl/go$REQUIRED_GO_VERSION.linux-amd64.tar.gz -o go.tar.gz
            rm -rf /usr/local/go
            tar -C /usr/local -xzf go.tar.gz
            echo 'export PATH=/usr/local/go/bin:$PATH' >> /etc/profile
            export PATH=/usr/local/go/bin:$PATH
            rm go.tar.gz
            echo " ✅ Go $REQUIRED_GO_VERSION установлен!"
            go version
          fi
          EOF

      - name: Удаление старых файлов
        run: |
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} "chmod -x /etc/update-motd.d/*"
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} 'rm -f ${{ env.PATH_SERVICE }}${{ env.NAME_APP }}.service || { echo "❌ Не удалось удалить systemd файл"; cd ${{ env.PATH_SERVICE }}; ls; }'
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} 'rm -rf ${{ env.ROOT_DIR }}${{ env.NAME_APP }}${{ env.GEN_DIR }} || { echo "❌ Не удалось удалить папку gen"; cd ${{ env.ROOT_DIR }}${{ env.NAME_APP }}${{ env.GEN_DIR }}; ls; }'
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} 'rm -rf ${{ env.ROOT_DIR }}${{ env.NAME_APP }}${{ env.PROTO_DIR }} || { echo "❌ Не удалось удалить папку proto"; cd ${{ env.ROOT_DIR }}${{ env.NAME_APP }}${{ env.PROTO_DIR }}; ls; }'
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} 'rm -rf ${{ env.ROOT_DIR }}${{ env.NAME_APP }}/build/ || { echo "❌ Не удалось удалить папку build"; cd ${{ env.ROOT_DIR }}${{ env.NAME_APP }}/build/; ls; }'
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} 'mkdir -p ${{ env.ROOT_DIR }}${{ env.NAME_APP }}/build/'
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} 'ls -la ${{ env.ROOT_DIR }}${{ env.NAME_APP }}/build/'

      - name: Копирование файлов на удаленный сервер
        run: |
          sudo apt-get install -y ssh rsync
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} 'mkdir -p ${{ env.ROOT_DIR }}${{ env.NAME_APP }}/'
          rsync -avz --exclude='.git' ./ root@${{ env.SERVER_IP }}:${{ env.ROOT_DIR }}${{ env.NAME_APP }}/

      - name: Сборка приложения
        run: |
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << 'EOF'
          set -euo pipefail
          mkdir -p ${{ env.ROOT_DIR }}${{env.NAME_APP}}/build/
          cd ${{ env.ROOT_DIR }}${{env.NAME_APP}}
          if GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
          go build -o "${{ env.ROOT_DIR }}${{env.NAME_APP}}/build/${{env.NAME_APP}}" "${{ env.ROOT_DIR }}${{env.NAME_APP}}${{env.GO_MAIN_FILE}}"; then 
          echo "✅ ✅ Приложение собрано!"
          else
          echo "❌ ❌ Сборка не удалась — пожалуйста, проверьте наличие go.mod и устраните ошибки." >&2
          exit 1
          fi
          EOF

      - name: Проверка и установка Proto и плагинов
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << 'EOF'
          export PATH=$PATH:/usr/local/go/bin:$(go env GOPATH)/bin
          set -euo pipefail
          echo "🔄 Обновляем список пакетов…"
          apt-get update
          if ! command -v protoc >/dev/null; then
            echo "🔧 Устанавливаем Protoc..."
            apt-get install -y protobuf-compiler && echo " ✅ Protoc установлен!" || { echo "❌ Ошибка установки Protoc"; exit 1; }
          else
            echo "✅ Protoc УЖЕ установлен!"
          fi
          if ! command -v protoc-gen-go >/dev/null; then
            echo "🔧 Устанавливаем protoc-gen-go..."
            go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && echo " ✅ Плагин Protoc-gen-go установлен!" || { echo "❌ Ошибка установки плагина Protoc-gen-go"; exit 1; }
          else
            echo "✅ Плагин Protoc-gen-go-grpc УЖЕ установлен!"
          fi
          if ! command -v protoc-gen-go-grpc >/dev/null; then
            echo "🔧 Устанавливаем protoc-gen-go-grpc..."
            go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest && echo " ✅ Плагин Protoc-gen-go-grpc установлен!" || { echo "❌ Ошибка установки плагина Protoc-gen-go-grpc"; exit 1; }
          else
            echo "✅ Плагин Protoc-gen-go-grpc УЖЕ установлен!"
          fi
          echo "✅ Все компоненты Proto и плагины установлены!"
          EOF

      - name: Генерация Proto-кода
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << 'EOF'
          set -euo pipefail 
          mkdir -p ${{ env.ROOT_DIR }}${{env.NAME_APP}}${{ env.GEN_DIR }} && echo " ✅ Папка для ген-кода создана!" || echo " ❌ Ошибка при создании папки!"
          protoc -I=${{ env.ROOT_DIR }}${{ env.NAME_APP }}/proto \
            --go_out=${{ env.ROOT_DIR }}${{ env.NAME_APP }}${{ env.GEN_DIR }} \
            --go_opt=paths=source_relative \
            --go-grpc_out=${{ env.ROOT_DIR }}${{ env.NAME_APP }}${{ env.GEN_DIR }} \
            --go-grpc_opt=paths=source_relative \
            ${{ env.ROOT_DIR }}${{ env.NAME_APP }}/proto/*.proto && echo "✅ Proto-Код сгенерирован!" || { echo "❌ Proto-Код не сгенерирован!"; exit 1; }
          EOF

      - name: Установка MongoDB
        run: |
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << 'EOF'
          if ! dpkg -l | grep -q mongodb-org; then
          echo " ==== Установка MongoDB . . .  ==== "
          curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | gpg --dearmor > mongodb-server-7.0.gpg
          mv mongodb-server-7.0.gpg /etc/apt/trusted.gpg.d/
          wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | gpg --dearmor > /usr/share/keyrings/mongo.gpg
          echo 'deb [ signed-by=/usr/share/keyrings/mongo.gpg arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse' | tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          apt update || { echo "Ошибка обновления"; exit 1; }
          apt install -y mongodb-org || { echo "Ошибка установки MongoDB"; exit 1; }
          echo " ✅ ✅ Установка MongoDB завершена ==== "
          else
          echo " ✅ MongoDB уже установлен. Установка не требуется ==== "
          fi
          EOF

      - name: Создание Service-файла Mongo DB
        run: |
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << 'EOF'
          DB_SERVICE_PATH=${{ env.PATH_SERVICE }}mongodb_${{ env.NAME_APP }}.service
          if [ -f $DB_SERVICE_PATH ]; then
            rm $DB_SERVICE_PATH
          fi
          touch $DB_SERVICE_PATH
          chmod 600 $DB_SERVICE_PATH
          chown root:root $DB_SERVICE_PATH
          echo "[Unit]" | tee "$DB_SERVICE_PATH"
          echo "Description=Start MongoDB (Auth)" | tee -a "$DB_SERVICE_PATH"
          echo "After=network.target" | tee -a "$DB_SERVICE_PATH"
          echo "[Service]" | tee -a "$DB_SERVICE_PATH"
          echo "User=root" | tee -a "$DB_SERVICE_PATH"
          echo "Group=mongodb" | tee -a "$DB_SERVICE_PATH"
          echo "ExecStart=/usr/bin/mongod --port ${{ env.DB_PORT }} --dbpath=${{ env.DB_PATH }}${{ env.NAME_DB }}/ --auth" | tee -a "$DB_SERVICE_PATH"
          echo "Restart=always" | tee -a "$DB_SERVICE_PATH"
          echo "RestartSec=5" | tee -a "$DB_SERVICE_PATH"
          echo "[Install]" | tee -a "$DB_SERVICE_PATH"
          echo "WantedBy=multi-user.target" | tee -a "$DB_SERVICE_PATH"
          EOF

      - name: Создание Service-файла Mongo DB (TEMP)
        run: |
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << 'EOF'
          DB_SERVICE_PATH=${{ env.PATH_SERVICE }}mongodb_${{ env.NAME_APP }}_tmp.service 
          if [ -f "$DB_SERVICE_PATH" ]; then
            rm $DB_SERVICE_PATH
          fi
          touch $DB_SERVICE_PATH
          chmod 600 $DB_SERVICE_PATH
          chown root:root $DB_SERVICE_PATH
          
          echo "[Unit]" | tee "$DB_SERVICE_PATH"
          echo "Description=Start MongoDB (No Auth)" | tee -a "$DB_SERVICE_PATH"
          echo "After=network.target" | tee -a "$DB_SERVICE_PATH"
          echo "[Service]" | tee -a "$DB_SERVICE_PATH"
          echo "User=root" | tee -a "$DB_SERVICE_PATH"
          echo "Group=mongodb" | tee -a "$DB_SERVICE_PATH"
          echo "ExecStart=/usr/bin/mongod --port ${{ env.DB_PORT }} --dbpath=${{ env.DB_PATH }}${{ env.NAME_DB }}/ --noauth" | tee -a "$DB_SERVICE_PATH"
          echo "Restart=no" | tee -a "$DB_SERVICE_PATH"
          echo "[Install]" | tee -a "$DB_SERVICE_PATH"
          echo "WantedBy=multi-user.target" | tee -a "$DB_SERVICE_PATH"
          EOF

      - name: Останавливаем MongoDB
        run: |
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << 'EOF'
          echo "===== Останавливаем MongoDB . . .  ====== "
          DB_SERVICE_FILE=mongodb_${{ env.NAME_APP }}.service
          DB_SERVICE_PATH=${{ env.PATH_SERVICE }}mongodb_${{ env.NAME_APP }}.service
          DB_SERVICE_TMP_FILE=mongodb_${{ env.NAME_APP }}_tmp.service
          DB_SERVICE_TMP_PATH=${{ env.PATH_SERVICE }}mongodb_${{ env.NAME_APP }}_tmp.service
          mkdir -p ${{ env.DB_PATH }}${{ env.NAME_DB }}/
          
          systemctl disable $DB_SERVICE_FILE     
          if systemctl is-active --quiet $DB_SERVICE_PATH; then
          echo " ❌ ✅ MongoDB активен, останавливаем..."
          systemctl stop $DB_SERVICE_FILE
          else
          echo " ✅ MongoDB не запущен."
          fi

          systemctl disable $DB_SERVICE_TMP_FILE
          if systemctl is-active --quiet $DB_SERVICE_TMP_PATH; then
          echo " ❌ ✅ MongoDB(tmp) активен, останавливаем..."
          systemctl stop $DB_SERVICE_TMP_FILE
          else
          echo " ✅ MongoDB(tmp) не запущен"
          fi
          
          EOF

      - name: Создаем пользователя с правами на чтение и запись
        run: |
          ssh -t -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << 'EOF'
          DB_SERVICE_FILE=${{ env.PATH_SERVICE }}mongodb_${{ env.NAME_APP }}.service
          DB_SERVICE_TMP_FILE=mongodb_${{ env.NAME_APP }}_tmp.service
          
          pid=$(ss -tunlp | grep ":${{ env.DB_PORT }}" | awk '{print $7}' | cut -d ',' -f 2 | tr -d 'pid=' || echo "")
          
          if [ ! -z "$pid" ]; then
          echo " Найден PID процесса MongoDB: $pid "
          kill -9 $pid
          echo " ❌ ✅ MongoDB завершен принудительно"
          else
          echo " ✅ ✅ Процессы на порту ${{ env.DB_PORT }} закрыты и запускаем неавторизованный MongoDB"
          fi
          systemctl daemon-reload && systemctl restart $DB_SERVICE_TMP_FILE
          sleep 3

          mongosh --port ${{ env.DB_PORT }} --eval "
          
          db = db.getSiblingDB('admin');
          if (!db.getUser('${{ env.DB_USER }}')) {
            db.createUser({ user: '${{ env.DB_USER }}', pwd: '${{ secrets.DB_PASS }}', roles: [ { role: 'root', db: 'admin' } ] });
            print(' ✅ ✅ Пользователь ${{ env.DB_USER }} создан в admin.');
          } else {
            print(' ✅ Пользователь ${{ env.DB_USER }} уже существует в admin.');
          }

          db = db.getSiblingDB('${{ env.NAME_DB }}');
          if (!db.getUser('${{ env.DB_USER }}')) {
            db.createUser({ user: '${{ env.DB_USER }}', pwd: '${{ secrets.DB_PASS }}', roles: [ { role: 'dbOwner', db: '${{ env.NAME_DB }}' } ] });
            print(' ✅  ✅ Пользователь ${{ env.DB_USER }} создан в ${{ env.NAME_DB }}.');
          } else {
            print(' ✅ Пользователь ${{ env.DB_USER }} уже существует в ${{ env.NAME_DB }}.');
          }"
          
          systemctl stop $DB_SERVICE_TMP_FILE
          
          if ss -tunlp | grep ":${{ env.DB_PORT }}" > /dev/null; then
            echo " ❌ Остался открытым порт ${{ env.DB_PORT }}"
          else 
            echo " ✅ ✅ Все соединений на порту MongoDB успешно завершены!"
          fi
          EOF

      - name: Запуск MongoDB
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << 'EOF' 
          DB_SERVICE_FILE=mongodb_${{ env.NAME_APP }}.service
          systemctl daemon-reload && systemctl restart $DB_SERVICE_FILE && systemctl enable $DB_SERVICE_FILE && systemctl status $DB_SERVICE_FILE
          EOF

      - name: Создание systemd и запуск GO-приложения
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << 'EOF'          
          set -e
          SERVICE_APP="${{ env.PATH_SERVICE }}${{ env.NAME_APP }}.service"

          echo "🧹 Удаление предыдущего systemd unit-файла, если существует..."
          if systemctl is-active --quiet ${{ env.NAME_APP }}; then
            echo "⛔ Останавливаем текущее приложение..."
            systemctl stop ${{ env.NAME_APP }}
          fi
          if [ -f "$SERVICE_APP" ]; then
            echo "🗑 Удаляем старый unit-файл..."
            rm -f "$SERVICE_APP"
          fi

          tee "$SERVICE_APP" > /dev/null <<EOL
          [Unit]
          Description=Go Application
          After=network.target
          
          [Service]
          ExecStart=${{ env.ROOT_DIR }}${{env.NAME_APP}}/build/${{env.NAME_APP}} --config=${{ env.ROOT_DIR }}${{env.NAME_APP}}/configs/${{env.CONFIG_APP}}
          WorkingDirectory=${{ env.ROOT_DIR }}${{env.NAME_APP}}
          Restart=always
          StandardOutput=inherit
          User=root
          Environment=PORT=${{ env.GO_PORT }}
          
          [Install]
          WantedBy=multi-user.target
          EOL
          
          chmod 600 "$SERVICE_APP"
          chown root:root "$SERVICE_APP"
          
          systemctl daemon-reexec
          systemctl daemon-reload
          systemctl enable --now ${{ env.NAME_APP }}
          
          systemctl status ${{ env.NAME_APP }}
          if systemctl is-active --quiet ${{ env.NAME_APP }}; then
          echo "✅ ✅ Приложение ${{ env.NAME_APP }} успешно запущено и активно."
          else
          journalctl -u ${{ env.NAME_APP }} -n 50
          echo "❌ ❌ Приложение ${{ env.NAME_APP }} не запустилось." >&2
          exit 1
          fi
          EOF
